[package]
name = "nextcloud-config-parser"
description = "Rust parser for nextcloud config files"
version = "0.6.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icewind1991/nextcloud-config-parser"
documentation = "https://docs.rs/nextcloud-config-parser"

[dependencies]
redis = { version = "0.21", optional = true }
thiserror = "1"
php-literal-parser = "0.4"
sqlx = { version = "0.6", default-features = false, features = ["runtime-tokio-rustls", "any", "mysql", "sqlite", "postgres"], optional = true }
miette = "3"

[dev-dependencies]
sqlx = { version = "0.6", default-features = false, features = ["runtime-tokio-rustls", "any", "mysql", "sqlite", "postgres"] }
miette = { version = "3", features = ["fancy"] }

[features]
db-sqlx = ["sqlx"]
redis-connect = ["redis"]
