[package]
name = "nextcloud-config-parser"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
redis = { version = "0.20", features = ["tokio-comp", "aio", "cluster"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
warp = "0.3"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "any", "macros", "mysql", "sqlite", "postgres"] }
php-literal-parser =  { version = "0.2", default-features = false }
parse-display = "0.4"